In [1]:
# Importing necessary libraries
import pandas as pd

In [2]:
# Read the CSV file into a DataFrame
fruits = pd.read_csv('friuts_nutritional_facts.csv')
fruits.head()

,Name,Emotional value:,Health value:,Product group:,Energy (kcal),Energy (kJoule),Water,Protein,Fat,Saturated fat,...,Potassium (K),Calcium (Ca),Phosphorus (P),Iron (Fe),Magnesium (Mg),Copper (Cu),Zinc (Zn),Selenium (Se),Iodine (I),Manganese (Mn)
0,"Apple, fresh",8.4,-,Fruit,54,229,"84,3","0,4","0,0","0,0",...,120,"4,0","10,0","0,2","5,00","0,10","0,04",-,-,-
1,"Applesauce, canned, sweetened",7.2,-,Fruit,81,341,"78,5","0,2","0,1","0,0",...,114,"4,0","7,0","0,1","3,00","0,01","0,02",-,-,-
2,"Apricot, canned, no skin",5.9,-,Fruit,74,310,"80,3","0,5","0,1","0,0",...,196,"11,0","15,0","0,7","5,00","0,05","0,10",-,-,-
3,"Apricot, dried",6.2,-,Fruit,274,1145,"26,9","5,0","0,1","0,0",...,1400,"80,0","110,0","4,4","60,00","0,80","0,40",-,-,-
4,"Apricot, fresh",7.4,-,Fruit,60,252,"83,4","1,4","0,4","0,0",...,280,"16,0","20,0","0,0","10,00","0,00","0,00",-,-,-

In [3]:
# Display information about the DataFrame, including the data types of each column and memory usage
fruits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 40 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Name                       54 non-null     object
 1   Emotional value:           54 non-null     object
 2   Health value:              54 non-null     object
 3   Product group:             54 non-null     object
 4   Energy (kcal)              54 non-null     int64
 5   Energy (kJoule)            54 non-null     int64
 6   Water                      54 non-null     object
 7   Protein                    54 non-null     object
 8   Fat                        54 non-null     object
 9   Saturated fat              54 non-null     object
 10  Monounsaturated fat        54 non-null     object
 11  Polyunsaturated fat        54 non-null     object
 12  Trans fat                  54 non-null     object
 13  Cholesterol                54 non-null     object
 14  Carbohydrates              54 non-null     object
 15  Sugars                     54 non-null     object
 16  Polysaccharides            54 non-null     object
 17  Dietary fiber              54 non-null     object
 18  Vitamin A (Retinol)        54 non-null     object
 19  Vitamin B1 (Thiamine)      54 non-null     object
 20  Vitamin B (Repulfvin)      54 non-null     object
 21  Vitamin B3 (Niacin)        54 non-null     object
 22  Vitamin B6 (Pyridoxine)    54 non-null     object
 23  Vitamin B11 (Folic acid)   54 non-null     object
 24  Vitamin B12 (Cobalamin)    54 non-null     object
 25  Vitamin C (Ascorbic Acid)  54 non-null     object
 26  Vitamin D (Calcifine)      54 non-null     object
 27  Vitamin E (Tocopherol)     54 non-null     object
 28  Vitamin K (Phyloquinone)   54 non-null     object
 29  Sodium (Na)                54 non-null     object
 30  Potassium (K)              54 non-null     object
 31  Calcium (Ca)               54 non-null     object
 32  Phosphorus (P)             54 non-null     object
 33  Iron (Fe)                  54 non-null     object
 34  Magnesium (Mg)             54 non-null     object
 35  Copper (Cu)                54 non-null     object
 36  Zinc (Zn)                  54 non-null     object
 37  Selenium (Se)              54 non-null     object
 38  Iodine (I)                 54 non-null     object
 39  Manganese (Mn)             54 non-null     object
dtypes: int64(2), object(38)
memory usage: 17.0+ KB

In [4]:
# Checking duplicate values
fruits.duplicated().sum()

0

In [5]:
# Replace "-" with NaN
fruits.replace("-", float("nan"), inplace=True)

In [6]:
# Replace commas with periods
columns_to_convert = fruits.columns.difference(['Name', 'Product group:'])
fruits[columns_to_convert] = fruits[columns_to_convert].replace(',', '.', regex=True)

In [7]:
# Convert all columns except 'Name' and 'Product group' to float
fruits[columns_to_convert] = fruits[columns_to_convert].astype(float)

In [8]:
# Rename columns to remove trailing colon
fruits.rename(columns=lambda x: x.split(':')[0].strip(), inplace=True)

In [9]:
# Final in the required format
fruits.head()

,Name,Emotional value,Health value,Product group,Energy (kcal),Energy (kJoule),Water,Protein,Fat,Saturated fat,...,Potassium (K),Calcium (Ca),Phosphorus (P),Iron (Fe),Magnesium (Mg),Copper (Cu),Zinc (Zn),Selenium (Se),Iodine (I),Manganese (Mn)
0,"Apple, fresh",8.4,NaN,Fruit,54.0,229.0,84.3,0.4,0.0,0.0,...,120.0,4.0,10.0,0.2,5.0,0.10,0.04,NaN,NaN,NaN
1,"Applesauce, canned, sweetened",7.2,NaN,Fruit,81.0,341.0,78.5,0.2,0.1,0.0,...,114.0,4.0,7.0,0.1,3.0,0.01,0.02,NaN,NaN,NaN
2,"Apricot, canned, no skin",5.9,NaN,Fruit,74.0,310.0,80.3,0.5,0.1,0.0,...,196.0,11.0,15.0,0.7,5.0,0.05,0.10,NaN,NaN,NaN
3,"Apricot, dried",6.2,NaN,Fruit,274.0,1145.0,26.9,5.0,0.1,0.0,...,1400.0,80.0,110.0,4.4,60.0,0.80,0.40,NaN,NaN,NaN
4,"Apricot, fresh",7.4,NaN,Fruit,60.0,252.0,83.4,1.4,0.4,0.0,...,280.0,16.0,20.0,0.0,10.0,0.00,0.00,NaN,NaN,NaN

In [10]:
# Write the DataFrame to a CSV file
fruits.to_csv('fruits_nutritional_facts_preprocessed.csv', index=False)